name: Greeting someone

on:
  workflow_call:
    inputs:
      full-name:
        type: string
        description: "The full name that is used to say hello to."
        required: true
      age:
        type: number
        description: "Your age that will be included in the greeting."
        required: false
        default: 0

jobs:
  saying-hello:
    name: Saying hello
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echoing
        run: echo "${{ inputs.full-name }}"

      - name: Showing age
        if: age > 0
        run: echo "Your age is ${{ inputs.age }}"